sudo: required
services:
  - docker

before_install: 
  - docker build -t dungngotan99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dungngotan99/react-test npm test -- --coverage

after_success:
  - docker build -t dungngotan99/multi-client ./client 
  - docker build -t dungngotan99/multi-nginx ./nginx
  - docker build -t dungngotan99/multi-server ./server
  - docker build -t dungngotan99/mutli-woker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push dungngotan99/multi-client
  - docker push dungngotan99/multi-nginx
  - docker push dungngotan99/multi-server
  - docker push dungngotan99/multi-worker